# Generated by Django 5.0.4 on 2024-06-27 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category Table',
                'verbose_name_plural': 'Categories Table',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='項目')),
                ('date', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='時刻')),
                ('amount', models.IntegerField()),
                ('category', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='accountbook.category', verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name': 'Account Table',
                'verbose_name_plural': 'Account Table',
                'db_table': 'Household Account',
            },
        ),
    ]
