# Generated by Django 5.0.6 on 2024-07-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.IntegerField(verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100, verbose_name='カテゴリ'),
        ),
    ]
