# Generated by Django 5.0.6 on 2024-07-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0002_alter_account_amount_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='日付'),
        ),
    ]
